# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  
  - package-ecosystem: "cargo"
    directory: "/adapter"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "cargo"
    directory: "/macros"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "cargo"
    directory: "/example"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10